#!/usr/bin/env bash
#
# One-time provisioning for a fresh Ubuntu 22.04/24.04 VPS.
#
#   scp deploy/provision.sh root@<ip>:/root/
#   ssh root@<ip> 'ROOT_DOMAIN=enfinito.cloud ACME_EMAIL=you@example.com bash /root/provision.sh'
#
# Idempotent: safe to re-run. It never overwrites an existing .env.production,
# because that file holds generated secrets and clobbering it would invalidate
# every session and every stored password hash's pepper.
set -euo pipefail

ROOT_DOMAIN="${ROOT_DOMAIN:-enfinito.cloud}"
ACME_EMAIL="${ACME_EMAIL:-admin@${ROOT_DOMAIN}}"
ADMIN_BOOTSTRAP_EMAIL="${ADMIN_BOOTSTRAP_EMAIL:-}"
APP_DIR=/srv/ncom
APP_USER=ncom

log() { printf '\n\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\n\033[1;33m!!\033[0m %s\n' "$*"; }

[[ $EUID -eq 0 ]] || { echo "Run as root."; exit 1; }

log "Base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl git gnupg ufw fail2ban rsync debian-keyring \
  debian-archive-keyring apt-transport-https

# A Next.js production build is memory-hungry; the smaller VPS tiers OOM partway
# through and leave a half-written .next that fails at runtime in confusing ways.
if [[ ! -f /swapfile ]] && [[ $(free -m | awk '/^Mem:/{print $2}') -lt 4096 ]]; then
  log "Adding 2G swap (build headroom)"
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >>/etc/fstab
fi

if ! command -v node >/dev/null || [[ $(node -v | cut -d. -f1 | tr -d v) -lt 22 ]]; then
  log "Node.js 22"
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash - >/dev/null
  apt-get install -y -qq nodejs
fi

log "pnpm"
corepack enable
corepack prepare pnpm@latest --activate >/dev/null

if ! command -v docker >/dev/null; then
  log "Docker"
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    >/etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi

if ! command -v caddy >/dev/null; then
  log "Caddy"
  curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/gpg.key |
    gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt |
    tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update -qq
  apt-get install -y -qq caddy
fi

log "Firewall"
ufw allow 22/tcp >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null
systemctl enable --now fail2ban >/dev/null

log "App user and directory"
id -u "$APP_USER" >/dev/null 2>&1 || useradd --system --create-home --shell /usr/sbin/nologin "$APP_USER"
mkdir -p "$APP_DIR"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

if [[ ! -f "$APP_DIR/.env.production" ]]; then
  log "Generating .env.production"
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  cat >"$APP_DIR/.env.production" <<EOF
# Generated by deploy/provision.sh on $(date -u +%FT%TZ). Secrets below are
# unique to this machine — back this file up, do not commit it.

DATABASE_URL="postgresql://ncom:${POSTGRES_PASSWORD}@127.0.0.1:5432/ncom"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
REDIS_URL="redis://127.0.0.1:6379"

AUTH_SECRET="$(openssl rand -base64 32)"
AUTH_URL="https://${ROOT_DOMAIN}"

ROOT_DOMAIN="${ROOT_DOMAIN}"
PLATFORM_HOSTS=""
DOMAIN_TARGET_IP="$(curl -fsS4 https://ifconfig.me 2>/dev/null || echo '')"

# Restricts the one-shot SUPER_ADMIN claim to this address. Set it BEFORE the
# first visitor reaches the site, or whoever registers first owns the platform.
ADMIN_BOOTSTRAP_EMAIL="${ADMIN_BOOTSTRAP_EMAIL}"

CRON_SECRET="$(openssl rand -hex 32)"
TLS_CHECK_SECRET="$(openssl rand -hex 32)"

# TODO: fill these in from the EnCDN admin panel (Clients > View credentials).
# The app refuses to boot while they are empty — src/lib/env.ts validates them.
CDN_BASE_URL="https://cdn.enfinito.cloud"
CDN_API_KEY=""
CDN_API_SECRET=""
CDN_SIGNED_URLS="true"
EOF
  chown "$APP_USER:$APP_USER" "$APP_DIR/.env.production"
  chmod 600 "$APP_DIR/.env.production"
else
  log ".env.production exists — leaving it alone"
fi

log "Caddy config"
install -o root -g root -m 644 "$(dirname "$0")/Caddyfile" /etc/caddy/Caddyfile 2>/dev/null ||
  warn "Caddyfile not next to this script — copy deploy/Caddyfile to /etc/caddy/Caddyfile yourself"

# Caddy reads ACME_EMAIL and TLS_CHECK_SECRET from its unit environment.
mkdir -p /etc/systemd/system/caddy.service.d
cat >/etc/systemd/system/caddy.service.d/override.conf <<EOF
[Service]
EnvironmentFile=${APP_DIR}/.env.production
Environment=ACME_EMAIL=${ACME_EMAIL}
EOF

log "systemd unit"
install -o root -g root -m 644 "$(dirname "$0")/ncom.service" /etc/systemd/system/ncom.service 2>/dev/null || true
systemctl daemon-reload
systemctl enable ncom >/dev/null 2>&1 || true

log "Done."
cat <<EOF

Next:
  1. Fill CDN_API_KEY / CDN_API_SECRET in ${APP_DIR}/.env.production
     (the app will not boot without them).
  2. Set ADMIN_BOOTSTRAP_EMAIL if it is still empty.
  3. From your workstation:  ./deploy/deploy.sh
  4. Point DNS at this box:
       A  ${ROOT_DOMAIN}          -> $(curl -fsS4 https://ifconfig.me 2>/dev/null || echo '<this ip>')
       A  *.${ROOT_DOMAIN}        -> $(curl -fsS4 https://ifconfig.me 2>/dev/null || echo '<this ip>')
       A  sites.${ROOT_DOMAIN}    -> $(curl -fsS4 https://ifconfig.me 2>/dev/null || echo '<this ip>')

EOF
